### ISSUE TITLE
The `visualParent` attribute will break Avalon from saving .inventory.toml

### ISSUE THREAD

**Issue by davidlatwe** [getavalon/core#347] opened 2018-10-31 07:52 UTC
### Problem

In your `.inventory.toml`, if you adding the attribute `group` for grouping assets visually in Launcher, 
like this
```toml
[[films]]
label = "S001"
group = "Shots"
tasks = [ "animate", "layout",]
name = "Shots_S001"
```
After saving this with `$ avalon --save`, there will be an extra attribute `visualParent` which content the visual parent's `ObjectID` write into database.

Now if you load them back from database with `$ avalon --load`, the `.inventory.toml` will be like
```toml
[[films]]
label = "S001"
visualParent = 5ba1f78fed9f0d812c2f9484
group = "Shots"
tasks = [ "animate", "layout",]
name = "Shots_S001"
```
Then when you save it again with `$ avalon --save`, this error will pop-up in your terminal
```
could not convert string to float: '5ba1f78fed9f0d812c2f9484'
```

**Comment by mottosso** [comment] 2018-10-31 07:56
Thanks @davidlatwe. :) What happens if you edit that toml, and put the parent in quotes?

```toml
[[films]]
visualParent = "5ba1f78fed9f0d812c2f9484"
```

It may work, but I think we might also need to actually convert it to a Mongo ID.

**Comment by davidlatwe** [comment] 2018-10-31 08:04
Surprisingly, only putting it in quotes and save it back won't affect the grouping in Launcher :O

**Comment by tokejepsen** [comment] 2018-10-31 15:24
This is a duplicate of #325

**Comment by mottosso** [comment] 2018-10-31 15:35
Looks like it. Hadn't seen #325 before, should be an easy fix.

**Closed by mottosso** 2018-10-31 15:35 UTC
Labels: bug

**Comment by davidlatwe** [comment] 2018-10-31 16:51
> Surprisingly, only putting it in quotes and save it back won't affect the grouping in Launcher :O

Just realize that, Launcher use `group`, and the `visualParent` was internally set from ProjectManager, that's why Launcher was not affected :(
