### ISSUE TITLE
Fusion Intergration: Gather more information in ls()

### ISSUE THREAD

**Issue by aardschok** [getavalon/core#315] opened 2018-05-02 10:36 UTC
Together with the introduction of [Inventory Actions](https://github.com/Colorbleed/core/pull/19) we would like to extend the amount of information gathered within Fusion.

## Our Goal
We have a request from our artists to incorporate the color of the Fusion Loader node in the inventory to get a better overview of the assets which have been loaded. We want to do this by updating the color of the folder icon.

## What will need to change
The scene inventory will need to support the customization of icon colors based on the data collected. In Fusion the `tool.TileColor` will need to be added to the container data.

[Here](https://github.com/getavalon/core/blob/6a2c8edec2fc5cd018d0496d094f8885cde8060c/avalon/tools/cbsceneinventory/model.py#L53) we set the default color. The color could be retrieved through the node instance under the [internalPointer](https://github.com/getavalon/core/blob/master/avalon/tools/cbsceneinventory/model.py#L62), we will fallback to the default color when no custom color has been found.

Dummy code:
```python
node = index.internalPointer()
hex_color = node.get("color", style.colors.default)
qta.icon("fa.folder", color=hex_color)
```

## Other use case:
I could see some other use cases in other applications or more general uses
* Color code representations or families
* Override draw color in Maya

**Comment by BigRoy** [comment] 2018-05-02 10:47
Note that the problem is two-fold:

1. Expose a way to allow a studio configuration to add in additional data (like color) into the collected container, so that when `api.ls()` is called in the scene inventory that it contains the required information.
2. Use a specific key-value from the container as color data to color the row, `color` makes sense. (trivial, purely Qt)

---

I think point one is the only interesting thing to discuss here. Plus, should `api.ls()` really always return it? Additional data like "color" seems to be a bit too much for something as simple as what a container must hold.

Maybe we should just allow a config to implement something like:

```python
import config  # assume this is studio configuration
import avalon.api as api

for container in api.ls():
    data = config.get_additional_data(container)
```

Or however one needs to expose it in the configuration so that the avalon core can call it in the tools.

**Comment by aardschok** [comment] 2018-05-03 10:50
We currently have this [one](https://github.com/aardschok/core/blob/FUS39/avalon/tools/cbsceneinventory/model.py) tested and checked. 

What are your thoughts on it @mottosso ?

**Comment by BigRoy** [comment] 2018-05-03 11:08
Would you be able to set it up as a PR to another Colorbleed repo? - would be good to easily spot the differences. :)

**Comment by aardschok** [comment] 2018-05-03 12:59
Created the PR: https://github.com/Colorbleed/core/pull/20

**Comment by mottosso** [comment] 2018-06-29 14:52
Welcome to merge this with core.

**Comment by BigRoy** [comment] 2018-10-09 06:30
Merged with: https://github.com/getavalon/core/pull/321

**Closed by BigRoy** 2018-10-09 06:30 UTC
Labels: enhancement, feature
